---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.nephio.org
  resources:
  - clusters
  - clusterscaleprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  - packagerevisions
  verbs:
  - create
  - get
  - list
  - update
