apiVersion: automation.nephio.org/v1alpha1
kind: PackageDeployment
metadata:
  name: aggregation-caching-dns
spec:
  selector:
    matchLabels:
      nephio.org/region: cn-wrcp-aiodx
      nephio.org/site-type: aggregation
  namespace: caching-dns
  packageRef:
    repository: nephio-packages
    packageName: coredns-caching-scaled
    revision: v1
